import { FeatureDefinition, GeneratedFile } from '../../../core/types';

export function generateApiConnector(feature: FeatureDefinition): GeneratedFile[] {
  return [
    {
      path: 'frontend/src/services/http/client.ts',
      content: [
        "import axios from 'axios';",
        '',
        'export interface ApiErrorPayload {',
        '  message: string;',
        '  statusCode: number;',
        '  details?: unknown;',
        '}',
        '',
        'export class ApiError extends Error {',
        '  constructor(public readonly payload: ApiErrorPayload) {',
        '    super(payload.message);',
        '    this.name = "ApiError";',
        '  }',
        '}',
        '',
        'const apiClient = axios.create({',
        '  baseURL: import.meta.env.VITE_API_BASE_URL || "http://localhost:4000/api",',
        '  timeout: 15000,',
        '  headers: {',
        '    "Content-Type": "application/json",',
        '  },',
        '});',
        '',
        'apiClient.interceptors.request.use((config) => {',
        '  config.headers.set("x-feature-name", "' + feature.feature + '");',
        '  return config;',
        '});',
        '',
        'apiClient.interceptors.response.use(',
        '  (response) => response,',
        '  (error) => {',
        '    const message = error?.response?.data?.message || error?.message || "Unexpected request error";',
        '    const statusCode = Number(error?.response?.status || 500);',
        '    const details = error?.response?.data?.details;',
        '    return Promise.reject(new ApiError({ message, statusCode, details }));',
        '  },',
        ');',
        '',
        'export { apiClient };',
      ].join('\n'),
    },
    {
      path: 'frontend/src/services/http/request.ts',
      content: [
        "import { AxiosRequestConfig } from 'axios';",
        "import { apiClient } from './client';",
        '',
        'export async function request<T>(config: AxiosRequestConfig): Promise<T> {',
        '  const response = await apiClient.request<T>(config);',
        '  return response.data;',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/services/campaignApi.ts',
      content: [
        "import { request } from './http/request';",
        '',
        'export interface Campaign {',
        '  id: string;',
        '  name: string;',
        '  message: string;',
        '  status: string;',
        '  createdAt: string;',
        '  updatedAt?: string;',
        '}',
        '',
        'export interface CampaignStatus {',
        '  id: string;',
        '  name: string;',
        '  status: string;',
        '  updatedAt: string;',
        '  dispatches: Array<{',
        '    id: string;',
        '    status: string;',
        '    sentAt?: string | null;',
        '  }>;',
        '}',
        '',
        'export function listCampaigns() {',
        '  return request<Campaign[]>({ method: "GET", url: "/campaigns" });',
        '}',
        '',
        'export function createCampaign(payload: { name: string; message: string }) {',
        '  return request<Campaign>({ method: "POST", url: "/campaigns", data: payload });',
        '}',
        '',
        'export function sendCampaign(campaignId: string) {',
        '  return request<Campaign>({ method: "POST", url: `/campaigns/${campaignId}/send` });',
        '}',
        '',
        'export function trackCampaignStatus(campaignId: string) {',
        '  return request<CampaignStatus>({ method: "GET", url: `/campaigns/${campaignId}/status` });',
        '}',
      ].join('\n'),
    },
  ];
}
