import { buildFrontendPrompt } from '../../../core/prompt-builder';
import { FeatureDefinition, GeneratedFile } from '../../../core/types';
import { frontendTemplate } from '../../../templates/frontend/campaign-system.template';

export function generateFrontend(feature: FeatureDefinition): GeneratedFile[] {
  const generationPrompt = buildFrontendPrompt(feature);

  const files: GeneratedFile[] = [
    {
      path: 'frontend/package.json',
      content: JSON.stringify(
        {
          name: `${feature.feature}-frontend`,
          private: true,
          version: '1.0.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc -b && vite build',
            preview: 'vite preview',
          },
          dependencies: {
            axios: '^1.13.0',
            clsx: '^2.1.1',
            react: '^18.3.1',
            'react-dom': '^18.3.1',
          },
          devDependencies: {
            '@types/react': '^18.3.23',
            '@types/react-dom': '^18.3.7',
            '@vitejs/plugin-react': '^4.5.0',
            autoprefixer: '^10.4.21',
            postcss: '^8.5.3',
            tailwindcss: '^3.4.17',
            typescript: '^5.8.3',
            vite: '^5.4.19',
          },
        },
        null,
        2,
      ),
    },
    {
      path: 'frontend/tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            module: 'ESNext',
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            skipLibCheck: true,
            moduleResolution: 'Bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
          },
          include: ['src'],
        },
        null,
        2,
      ),
    },
    {
      path: 'frontend/vite.config.ts',
      content: [
        "import { defineConfig } from 'vite';",
        "import react from '@vitejs/plugin-react';",
        '',
        'export default defineConfig({ plugins: [react()] });',
      ].join('\n'),
    },
    {
      path: 'frontend/postcss.config.js',
      content: [
        'export default {',
        '  plugins: {',
        '    tailwindcss: {},',
        '    autoprefixer: {},',
        '  },',
        '};',
      ].join('\n'),
    },
    {
      path: 'frontend/tailwind.config.ts',
      content: [
        "import type { Config } from 'tailwindcss';",
        '',
        'export default {',
        '  content: ["./index.html", "./src/**/*.{ts,tsx}"],',
        '  darkMode: "class",',
        '  theme: {',
        '    extend: {',
        '      colors: {',
        '        ink: "#090f19",',
        '        panel: "#121a28",',
        '        panelSoft: "#1a2438",',
        '        cyan: "#22d3ee",',
        '        lime: "#a3e635",',
        '        roseSoft: "#fb7185",',
        '      },',
        '      fontFamily: {',
        '        sans: ["Sora", "Manrope", "ui-sans-serif", "system-ui"],',
        '      },',
        '      boxShadow: {',
        '        panel: "0 20px 45px rgba(8, 18, 33, 0.4)",',
        '      },',
        '    },',
        '  },',
        '} satisfies Config;',
      ].join('\n'),
    },
    {
      path: 'frontend/index.html',
      content: [
        '<!doctype html>',
        '<html lang="en" class="dark">',
        '  <head>',
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        '    <link rel="preconnect" href="https://fonts.googleapis.com" />',
        '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />',
        '    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&family=Sora:wght@400;600;700&display=swap" rel="stylesheet" />',
        '    <title>Campaign System</title>',
        '  </head>',
        '  <body>',
        '    <div id="root"></div>',
        '    <script type="module" src="/src/main.tsx"></script>',
        '  </body>',
        '</html>',
      ].join('\n'),
    },
    {
      path: 'frontend/src/index.css',
      content: [
        '@tailwind base;',
        '@tailwind components;',
        '@tailwind utilities;',
        '',
        ':root {',
        '  color-scheme: dark;',
        '}',
        '',
        'body {',
        '  @apply m-0 min-h-screen bg-ink text-slate-100 antialiased;',
        '  background-image:',
        '    radial-gradient(circle at 15% -10%, rgba(34, 211, 238, 0.25), transparent 35%),',
        '    radial-gradient(circle at 85% -20%, rgba(163, 230, 53, 0.18), transparent 30%),',
        '    linear-gradient(120deg, #090f19 20%, #111827 100%);',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/main.tsx',
      content: [
        "import React from 'react';",
        "import ReactDOM from 'react-dom/client';",
        "import App from './App';",
        "import './index.css';",
        '',
        'ReactDOM.createRoot(document.getElementById("root")!).render(',
        '  <React.StrictMode>',
        '    <App />',
        '  </React.StrictMode>,',
        ');',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/ui/Button.tsx',
      content: [
        "import { ButtonHTMLAttributes } from 'react';",
        "import clsx from 'clsx';",
        '',
        'interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {',
        '  variant?: "primary" | "secondary" | "ghost";',
        '}',
        '',
        'export function Button({ variant = "primary", className, ...props }: ButtonProps) {',
        '  return (',
        '    <button',
        '      className={clsx(',
        '        "rounded-lg px-4 py-2 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-60",',
        '        variant === "primary" && "bg-cyan text-slate-950 hover:brightness-110",',
        '        variant === "secondary" && "border border-cyan/40 bg-cyan/10 text-cyan hover:bg-cyan/20",',
        '        variant === "ghost" && "text-slate-300 hover:bg-panelSoft",',
        '        className,',
        '      )}',
        '      {...props}',
        '    />',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/ui/Card.tsx',
      content: [
        "import { PropsWithChildren } from 'react';",
        "import clsx from 'clsx';",
        '',
        'interface CardProps extends PropsWithChildren {',
        '  className?: string;',
        '  title?: string;',
        '  subtitle?: string;',
        '}',
        '',
        'export function Card({ className, title, subtitle, children }: CardProps) {',
        '  return (',
        '    <section className={clsx("rounded-2xl border border-slate-800 bg-panel/80 p-4 shadow-panel", className)}>',
        '      {(title || subtitle) && (',
        '        <header className="mb-4">',
        '          {title && <h3 className="text-lg font-semibold">{title}</h3>}',
        '          {subtitle && <p className="text-sm text-slate-400">{subtitle}</p>}',
        '        </header>',
        '      )}',
        '      {children}',
        '    </section>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/ui/LoadingState.tsx',
      content: [
        'export function LoadingState({ label = "Loading data..." }: { label?: string }) {',
        '  return (',
        '    <div className="flex items-center gap-3 rounded-xl border border-slate-800 bg-panelSoft/70 p-4">',
        '      <span className="h-4 w-4 animate-spin rounded-full border-2 border-cyan/30 border-t-cyan" />',
        '      <p className="text-sm text-slate-300">{label}</p>',
        '    </div>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/ui/EmptyState.tsx',
      content: [
        "import { Button } from './Button';",
        '',
        'interface EmptyStateProps {',
        '  title: string;',
        '  description: string;',
        '  actionLabel?: string;',
        '  onAction?: () => void;',
        '}',
        '',
        'export function EmptyState({ title, description, actionLabel, onAction }: EmptyStateProps) {',
        '  return (',
        '    <div className="rounded-2xl border border-dashed border-slate-700 bg-panelSoft/50 p-8 text-center">',
        '      <h4 className="text-base font-semibold">{title}</h4>',
        '      <p className="mt-2 text-sm text-slate-400">{description}</p>',
        '      {actionLabel && onAction && (',
        '        <Button className="mt-4" onClick={onAction}>',
        '          {actionLabel}',
        '        </Button>',
        '      )}',
        '    </div>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/layout/DashboardLayout.tsx',
      content: [
        "import { PropsWithChildren } from 'react';",
        '',
        'export function DashboardLayout({ children }: PropsWithChildren) {',
        '  return (',
        '    <div className="mx-auto grid min-h-screen max-w-7xl grid-cols-1 gap-4 p-4 lg:grid-cols-[260px,1fr]">',
        '      <aside className="rounded-2xl border border-slate-800 bg-panel/85 p-6">',
        '        <h1 className="font-sans text-2xl font-bold tracking-tight">AI Campaign Hub</h1>',
        '        <p className="mt-2 text-sm text-slate-400">Production-ready campaign generation.</p>',
        '        <nav className="mt-8 space-y-2 text-sm">',
        '          <button className="w-full rounded-xl bg-panelSoft px-3 py-2 text-left">Campaigns</button>',
        '          <button className="w-full rounded-xl px-3 py-2 text-left text-slate-400 hover:bg-panelSoft">Contacts</button>',
        '          <button className="w-full rounded-xl px-3 py-2 text-left text-slate-400 hover:bg-panelSoft">Settings</button>',
        '        </nav>',
        '      </aside>',
        '      <main className="rounded-2xl border border-slate-800 bg-slate-950/75 p-6">',
        '        <header className="mb-6 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">',
        '          <div>',
        '            <h2 className="text-2xl font-semibold">WhatsApp Campaign System</h2>',
        `            <p className="text-xs text-slate-400">${generationPrompt.replace(/"/g, '&quot;')}</p>`,
        '          </div>',
        '          <span className="rounded-full border border-lime/50 bg-lime/10 px-3 py-1 text-xs text-lime">Engine Ready</span>',
        '        </header>',
        '        {children}',
        '      </main>',
        '    </div>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/CampaignBuilder.tsx',
      content: [
        "import { FormEvent, useState } from 'react';",
        "import { Button } from './ui/Button';",
        "import { Card } from './ui/Card';",
        '',
        'interface CampaignBuilderProps {',
        '  onCreate: (payload: { name: string; message: string }) => Promise<void>;',
        '  busy: boolean;',
        '}',
        '',
        'export function CampaignBuilder({ onCreate, busy }: CampaignBuilderProps) {',
        '  const [name, setName] = useState("");',
        '  const [message, setMessage] = useState("");',
        '',
        '  async function handleSubmit(event: FormEvent) {',
        '    event.preventDefault();',
        '    await onCreate({ name, message });',
        '    setName("");',
        '    setMessage("");',
        '  }',
        '',
        '  return (',
        '    <Card title="Campaign Builder" subtitle="Create and validate campaign payload before dispatch">',
        '      <form onSubmit={handleSubmit} className="space-y-3">',
        '        <input',
        '          className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm outline-none focus:border-cyan"',
        '          placeholder="Campaign name"',
        '          value={name}',
        '          onChange={(event) => setName(event.target.value)}',
        '        />',
        '        <textarea',
        '          className="h-28 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm outline-none focus:border-cyan"',
        '          placeholder="Message body"',
        '          value={message}',
        '          onChange={(event) => setMessage(event.target.value)}',
        '        />',
        '        <Button disabled={busy || !name.trim() || !message.trim()}>',
        '          {busy ? "Saving..." : "Create Campaign"}',
        '        </Button>',
        '      </form>',
        '    </Card>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/CampaignList.tsx',
      content: [
        "import { Campaign } from '../services/campaignApi';",
        "import { Button } from './ui/Button';",
        "import { Card } from './ui/Card';",
        "import { EmptyState } from './ui/EmptyState';",
        '',
        'interface CampaignListProps {',
        '  campaigns: Campaign[];',
        '  loading: boolean;',
        '  onSend: (campaignId: string) => Promise<void>;',
        '}',
        '',
        'export function CampaignList({ campaigns, loading, onSend }: CampaignListProps) {',
        '  return (',
        '    <Card title="Campaign List" subtitle="Review status and trigger message dispatch">',
        '      {loading ? (',
        '        <p className="text-sm text-slate-400">Refreshing campaigns...</p>',
        '      ) : campaigns.length === 0 ? (',
        '        <EmptyState',
        '          title="No campaigns yet"',
        '          description="Create your first campaign to start dispatching messages."',
        '        />',
        '      ) : (',
        '        <ul className="space-y-3">',
        '          {campaigns.map((campaign) => (',
        '            <li',
        '              key={campaign.id}',
        '              className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-3 md:flex-row md:items-center md:justify-between"',
        '            >',
        '              <div>',
        '                <p className="font-medium">{campaign.name}</p>',
        '                <p className="text-xs text-slate-400">Status: {campaign.status}</p>',
        '              </div>',
        '              <Button variant="secondary" onClick={() => onSend(campaign.id)}>',
        '                Send Messages',
        '              </Button>',
        '            </li>',
        '          ))}',
        '        </ul>',
        '      )}',
        '    </Card>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/PreviewPanel.tsx',
      content: [
        "import { Campaign } from '../services/campaignApi';",
        "import { Card } from './ui/Card';",
        '',
        'interface PreviewPanelProps {',
        '  campaign?: Campaign;',
        '}',
        '',
        'export function PreviewPanel({ campaign }: PreviewPanelProps) {',
        '  return (',
        '    <Card title="Preview Panel" subtitle="Validate outbound message before send">',
        '      {campaign ? (',
        '        <div className="rounded-xl border border-slate-800 bg-slate-900/70 p-3">',
        '          <p className="text-sm text-slate-300">{campaign.message}</p>',
        '        </div>',
        '      ) : (',
        '        <p className="text-sm text-slate-400">Select a campaign to preview content.</p>',
        '      )}',
        '    </Card>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/components/HistoryPanel.tsx',
      content: [
        "import { Campaign } from '../services/campaignApi';",
        "import { Card } from './ui/Card';",
        '',
        'interface HistoryPanelProps {',
        '  campaigns: Campaign[];',
        '}',
        '',
        'export function HistoryPanel({ campaigns }: HistoryPanelProps) {',
        '  return (',
        '    <Card title="History" subtitle="Recent campaign operations">',
        '      <ul className="space-y-2 text-sm">',
        '        {campaigns.map((campaign) => (',
        '          <li key={campaign.id} className="flex items-center justify-between rounded-lg bg-slate-900/60 px-3 py-2">',
        '            <span>{campaign.name}</span>',
        '            <span className="text-slate-400">{new Date(campaign.createdAt).toLocaleString()}</span>',
        '          </li>',
        '        ))}',
        '      </ul>',
        '    </Card>',
        '  );',
        '}',
      ].join('\n'),
    },
    {
      path: 'frontend/src/App.tsx',
      content: [
        "import { useEffect, useMemo, useState } from 'react';",
        "import { CampaignBuilder } from './components/CampaignBuilder';",
        "import { CampaignList } from './components/CampaignList';",
        "import { HistoryPanel } from './components/HistoryPanel';",
        "import { PreviewPanel } from './components/PreviewPanel';",
        "import { EmptyState } from './components/ui/EmptyState';",
        "import { LoadingState } from './components/ui/LoadingState';",
        "import { DashboardLayout } from './layout/DashboardLayout';",
        "import { ApiError } from './services/http/client';",
        "import { Campaign, createCampaign, listCampaigns, sendCampaign } from './services/campaignApi';",
        '',
        'export default function App() {',
        '  const [campaigns, setCampaigns] = useState<Campaign[]>([]);',
        '  const [isLoading, setIsLoading] = useState(true);',
        '  const [isSaving, setIsSaving] = useState(false);',
        '  const [error, setError] = useState<string | null>(null);',
        '',
        '  async function loadCampaigns() {',
        '    setIsLoading(true);',
        '    try {',
        '      const data = await listCampaigns();',
        '      setCampaigns(data);',
        '      setError(null);',
        '    } catch (caughtError) {',
        '      const apiError = caughtError as ApiError;',
        '      setError(apiError.message || "Failed to load campaigns");',
        '    } finally {',
        '      setIsLoading(false);',
        '    }',
        '  }',
        '',
        '  useEffect(() => {',
        '    void loadCampaigns();',
        '  }, []);',
        '',
        '  async function handleCreate(payload: { name: string; message: string }) {',
        '    setIsSaving(true);',
        '    try {',
        '      await createCampaign(payload);',
        '      await loadCampaigns();',
        '    } finally {',
        '      setIsSaving(false);',
        '    }',
        '  }',
        '',
        '  async function handleSend(campaignId: string) {',
        '    setIsSaving(true);',
        '    try {',
        '      await sendCampaign(campaignId);',
        '      await loadCampaigns();',
        '    } finally {',
        '      setIsSaving(false);',
        '    }',
        '  }',
        '',
        '  const previewCampaign = useMemo(() => campaigns[0], [campaigns]);',
        '',
        '  return (',
        '    <DashboardLayout>',
        '      {error && <p className="mb-4 rounded-lg border border-roseSoft/40 bg-roseSoft/10 p-3 text-sm text-rose-200">{error}</p>}',
        '      {isLoading ? (',
        '        <LoadingState label="Loading campaign data..." />',
        '      ) : campaigns.length === 0 ? (',
        '        <EmptyState',
        '          title="Campaign workspace is empty"',
        '          description="Use Campaign Builder to create your first message flow."',
        '        />',
        '      ) : null}',
        '      <div className="mt-4 grid gap-4 lg:grid-cols-2">',
        '        <CampaignBuilder onCreate={handleCreate} busy={isSaving} />',
        '        <PreviewPanel campaign={previewCampaign} />',
        '        <CampaignList campaigns={campaigns} loading={isLoading} onSend={handleSend} />',
        '        <HistoryPanel campaigns={campaigns} />',
        '      </div>',
        '    </DashboardLayout>',
        '  );',
        '}',
      ].join('\n'),
    },
  ];

  return [...files, ...frontendTemplate(feature)];
}
