import { buildBackendPrompt } from '../../../core/prompt-builder';
import { FeatureDefinition, GeneratedFile } from '../../../core/types';
import { backendTemplate } from '../../../templates/backend/campaign-system.template';

export function generateBackend(feature: FeatureDefinition): GeneratedFile[] {
  const generationPrompt = buildBackendPrompt(feature);

  const files: GeneratedFile[] = [
    {
      path: 'backend/package.json',
      content: JSON.stringify(
        {
          name: `${feature.feature}-backend`,
          private: true,
          version: '1.0.0',
          scripts: {
            dev: 'tsx watch src/server.ts',
            build: 'tsc -p tsconfig.json',
            start: 'node dist/server.js',
            prisma: 'prisma',
          },
          dependencies: {
            '@prisma/client': '^6.7.0',
            cors: '^2.8.5',
            dotenv: '^16.4.5',
            express: '^4.21.2',
            helmet: '^8.0.0',
            zod: '^3.25.34',
          },
          devDependencies: {
            '@types/cors': '^2.8.17',
            '@types/express': '^4.17.21',
            '@types/node': '^22.15.3',
            prisma: '^6.7.0',
            tsx: '^4.19.4',
            typescript: '^5.8.3',
          },
        },
        null,
        2,
      ),
    },
    {
      path: 'backend/tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            module: 'CommonJS',
            strict: true,
            rootDir: 'src',
            outDir: 'dist',
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
          },
          include: ['src/**/*.ts'],
        },
        null,
        2,
      ),
    },
    {
      path: 'backend/src/config/env.ts',
      content: [
        "import 'dotenv/config';",
        "import { z } from 'zod';",
        '',
        'const envSchema = z.object({',
        '  PORT: z.coerce.number().int().positive().default(4000),',
        '  DATABASE_URL: z.string().min(1),',
        '  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),',
        '});',
        '',
        'export const env = envSchema.parse(process.env);',
      ].join('\n'),
    },
    {
      path: 'backend/src/shared/errors/AppError.ts',
      content: [
        'export class AppError extends Error {',
        '  constructor(',
        '    public readonly statusCode: number,',
        '    message: string,',
        '    public readonly details?: unknown,',
        '  ) {',
        '    super(message);',
        '    this.name = "AppError";',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      path: 'backend/src/shared/http/asyncHandler.ts',
      content: [
        "import { NextFunction, Request, Response } from 'express';",
        '',
        'type Handler = (req: Request, res: Response, next: NextFunction) => Promise<unknown>;',
        '',
        'export function asyncHandler(handler: Handler) {',
        '  return (req: Request, res: Response, next: NextFunction) => {',
        '    void handler(req, res, next).catch(next);',
        '  };',
        '}',
      ].join('\n'),
    },
    {
      path: 'backend/src/shared/http/error-handler.ts',
      content: [
        "import { NextFunction, Request, Response } from 'express';",
        "import { ZodError } from 'zod';",
        "import { AppError } from '../errors/AppError';",
        '',
        'export function errorHandler(error: Error, _req: Request, res: Response, _next: NextFunction) {',
        '  if (error instanceof AppError) {',
        '    return res.status(error.statusCode).json({',
        '      message: error.message,',
        '      details: error.details || null,',
        '    });',
        '  }',
        '',
        '  if (error instanceof ZodError) {',
        '    return res.status(422).json({',
        '      message: "Validation failed",',
        '      details: error.flatten(),',
        '    });',
        '  }',
        '',
        '  return res.status(500).json({',
        '    message: "Internal server error",',
        '  });',
        '}',
      ].join('\n'),
    },
    {
      path: 'backend/src/shared/http/not-found.ts',
      content: [
        "import { Request, Response } from 'express';",
        '',
        'export function notFoundHandler(req: Request, res: Response) {',
        '  return res.status(404).json({',
        '    message: `Route not found: ${req.method} ${req.originalUrl}`,' ,
        '  });',
        '}',
      ].join('\n'),
    },
    {
      path: 'backend/src/infra/database/prisma.ts',
      content: [
        "import { PrismaClient } from '@prisma/client';",
        '',
        'export const prisma = new PrismaClient();',
      ].join('\n'),
    },
    {
      path: 'backend/src/modules/campaigns/campaign.dto.ts',
      content: [
        "import { z } from 'zod';",
        '',
        'export const createCampaignSchema = z.object({',
        '  name: z.string().min(3),',
        '  message: z.string().min(1),',
        '});',
        '',
        'export const sendCampaignSchema = z.object({',
        '  campaignId: z.string().cuid(),',
        '});',
        '',
        'export type CreateCampaignDTO = z.infer<typeof createCampaignSchema>;',
      ].join('\n'),
    },
    {
      path: 'backend/src/modules/campaigns/campaign.repository.ts',
      content: [
        "import { prisma } from '../../infra/database/prisma';",
        "import { CreateCampaignDTO } from './campaign.dto';",
        '',
        'export const campaignRepository = {',
        '  create(data: CreateCampaignDTO) {',
        '    return prisma.campaign.create({ data: { ...data, status: "draft" } });',
        '  },',
        '',
        '  list() {',
        '    return prisma.campaign.findMany({',
        '      orderBy: { createdAt: "desc" },',
        '      include: { dispatches: true },',
        '    });',
        '  },',
        '',
        '  findById(id: string) {',
        '    return prisma.campaign.findUnique({ where: { id } });',
        '  },',
        '',
        '  updateStatus(id: string, status: string) {',
        '    return prisma.campaign.update({',
        '      where: { id },',
        '      data: { status },',
        '    });',
        '  },',
        '',
        '  async ensureSeedContacts() {',
        '    const contacts = await prisma.contact.findMany({ take: 5 });',
        '    if (contacts.length > 0) {',
        '      return contacts;',
        '    }',
        '',
        '    await prisma.contact.createMany({',
        '      data: [',
        '        { name: "Lead One", phone: "+5511990000001", segment: "default" },',
        '        { name: "Lead Two", phone: "+5511990000002", segment: "default" },',
        '      ],',
        '      skipDuplicates: true,',
        '    });',
        '',
        '    return prisma.contact.findMany({ take: 5 });',
        '  },',
        '',
        '  async createDispatches(campaignId: string) {',
        '    const contacts = await campaignRepository.ensureSeedContacts();',
        '    return prisma.messageDispatch.createMany({',
        '      data: contacts.map((contact) => ({',
        '        campaignId,',
        '        contactId: contact.id,',
        '        status: "queued",',
        '      })),',
        '      skipDuplicates: true,',
        '    });',
        '  },',
        '',
        '  listDispatchByCampaign(campaignId: string) {',
        '    return prisma.messageDispatch.findMany({',
        '      where: { campaignId },',
        '      orderBy: { id: "desc" },',
        '    });',
        '  },',
        '};',
      ].join('\n'),
    },
    {
      path: 'backend/src/modules/campaigns/campaign.service.ts',
      content: [
        "import { AppError } from '../../shared/errors/AppError';",
        "import { campaignRepository } from './campaign.repository';",
        "import { createCampaignSchema, sendCampaignSchema } from './campaign.dto';",
        '',
        'const sendableStatuses = new Set(["draft", "paused"]);',
        '',
        'export const campaignService = {',
        '  async create(input: unknown) {',
        '    const data = createCampaignSchema.parse(input);',
        '    return campaignRepository.create(data);',
        '  },',
        '',
        '  list() {',
        '    return campaignRepository.list();',
        '  },',
        '',
        '  async send(campaignId: string) {',
        '    sendCampaignSchema.parse({ campaignId });',
        '    const campaign = await campaignRepository.findById(campaignId);',
        '',
        '    if (!campaign) {',
        '      throw new AppError(404, "Campaign not found");',
        '    }',
        '',
        '    if (!sendableStatuses.has(campaign.status)) {',
        '      throw new AppError(409, "Campaign is not in a sendable status", {',
        '        campaignId,',
        '        status: campaign.status,',
        '      });',
        '    }',
        '',
        '    await campaignRepository.updateStatus(campaignId, "sending");',
        '    await campaignRepository.createDispatches(campaignId);',
        '    return campaignRepository.updateStatus(campaignId, "sent");',
        '  },',
        '',
        '  async status(campaignId: string) {',
        '    const campaign = await campaignRepository.findById(campaignId);',
        '    if (!campaign) {',
        '      throw new AppError(404, "Campaign not found");',
        '    }',
        '',
        '    const dispatches = await campaignRepository.listDispatchByCampaign(campaignId);',
        '    return {',
        '      id: campaign.id,',
        '      name: campaign.name,',
        '      status: campaign.status,',
        '      dispatches,',
        '      updatedAt: campaign.updatedAt,',
        '    };',
        '  },',
        '};',
      ].join('\n'),
    },
    {
      path: 'backend/src/modules/campaigns/campaign.controller.ts',
      content: [
        "import { Request, Response } from 'express';",
        "import { campaignService } from './campaign.service';",
        '',
        'export const campaignController = {',
        '  async create(req: Request, res: Response) {',
        '    const result = await campaignService.create(req.body);',
        '    return res.status(201).json(result);',
        '  },',
        '',
        '  async list(_req: Request, res: Response) {',
        '    const result = await campaignService.list();',
        '    return res.json(result);',
        '  },',
        '',
        '  async send(req: Request, res: Response) {',
        '    const result = await campaignService.send(req.params.id);',
        '    return res.json(result);',
        '  },',
        '',
        '  async status(req: Request, res: Response) {',
        '    const result = await campaignService.status(req.params.id);',
        '    return res.json(result);',
        '  },',
        '};',
      ].join('\n'),
    },
    {
      path: 'backend/src/modules/campaigns/campaign.routes.ts',
      content: [
        "import { Router } from 'express';",
        "import { campaignController } from './campaign.controller';",
        "import { asyncHandler } from '../../shared/http/asyncHandler';",
        '',
        'export const campaignRouter = Router();',
        '',
        'campaignRouter.post("/campaigns", asyncHandler(campaignController.create));',
        'campaignRouter.get("/campaigns", asyncHandler(campaignController.list));',
        'campaignRouter.post("/campaigns/:id/send", asyncHandler(campaignController.send));',
        'campaignRouter.get("/campaigns/:id/status", asyncHandler(campaignController.status));',
      ].join('\n'),
    },
    {
      path: 'backend/src/app.ts',
      content: [
        "import cors from 'cors';",
        "import express from 'express';",
        "import helmet from 'helmet';",
        "import { campaignRouter } from './modules/campaigns/campaign.routes';",
        "import { errorHandler } from './shared/http/error-handler';",
        "import { notFoundHandler } from './shared/http/not-found';",
        '',
        `const generationPrompt = ${JSON.stringify(generationPrompt)};`,
        '',
        'export function createApp() {',
        '  const app = express();',
        '  app.use(helmet());',
        '  app.use(cors());',
        '  app.use(express.json({ limit: "1mb" }));',
        '',
        '  app.get("/health", (_req, res) => {',
        '    res.json({ status: "ok", generationPrompt });',
        '  });',
        '',
        '  app.use("/api", campaignRouter);',
        '  app.use(notFoundHandler);',
        '  app.use(errorHandler);',
        '',
        '  return app;',
        '}',
      ].join('\n'),
    },
    {
      path: 'backend/src/server.ts',
      content: [
        "import { createApp } from './app';",
        "import { env } from './config/env';",
        '',
        'const app = createApp();',
        '',
        'app.listen(env.PORT, () => {',
        '  console.log(`Backend running on http://localhost:${env.PORT}`);',
        '});',
      ].join('\n'),
    },
  ];

  return [...files, ...backendTemplate(feature)];
}
