const { uuid } = require('../kernel/ids');
const { NotFoundError, ValidationError } = require('../kernel/errors');
const { assertNoSecrets } = require('../eventing/event-store');

class CognitiveCore {
  constructor({ store, controlPlane, eventStore, events, policy, approvals, jobs, contextProviders = [] }) { this.store = store; this.cp = controlPlane; this.eventStore = eventStore; this.events = events; this.policy = policy; this.approvals = approvals; this.jobs = jobs; this.contextProviders = contextProviders; this.unsubscribers = []; }
  attach() { for (const status of ['succeeded', 'failed', 'dead_letter', 'cancelled']) this.unsubscribers.push(this.events.subscribe(`runtime.job.${status}`, (event) => this.onJobResult(event))); return this; }
  async createGoal(tenantId, actorId, input) { await this.cp.authorize(tenantId, actorId, 'governance:approve'); if (!input?.title || !input?.successCriteria?.length) throw new ValidationError('goal title and successCriteria are required'); const goal = { id: uuid(), tenantId, title: String(input.title), description: String(input.description || ''), successCriteria: input.successCriteria, priority: Number(input.priority || 50), status: 'ACTIVE', owner: actorId, createdAt: now() }; await this.store.update((state) => { state.cognitiveGoals.push(goal); return state; }); await this.publish(goal, 'cognitive.goal.created', actorId); return goal; }
  async context(tenantId, actorId) { await this.cp.authorize(tenantId, actorId, 'governance:read'); const snapshots = {}; for (const provider of this.contextProviders) snapshots[provider.name] = await provider.snapshot(tenantId, actorId); return { tenantId, builtAt: now(), snapshots }; }
  async cycle(tenantId, actorId) {
    await this.cp.authorize(tenantId, actorId, 'governance:read'); const state = await this.store.read(); let cursor = state.cognitiveCursors.find((item) => item.tenantId === tenantId); const events = await this.eventStore.list(tenantId, { limit: 1000 }); const cursorIndex = cursor ? events.findIndex((event) => event.id === cursor.eventId) : -1; const unseen = cursorIndex >= 0 ? events.slice(cursorIndex + 1) : cursor ? events.filter((event) => event.recordedAt > cursor.recordedAt) : events;
    const relevant = unseen.filter((event) => /failed|error|degraded|missing|dead_letter|registered/.test(event.type)); const observations = relevant.map((event) => ({ id: uuid(), tenantId, kind: /registered/.test(event.type) ? 'CHANGE' : 'DEGRADATION', description: `${event.type} on ${event.subject || event.stream}`, evidence: [`event:${event.id}`], sourceEventId: event.id, confidence: 1, observedAt: event.occurredAt, createdAt: now() }));
    await this.store.update((draft) => { for (const observation of observations) if (!draft.cognitiveObservations.some((item) => item.sourceEventId === observation.sourceEventId)) draft.cognitiveObservations.push(observation); const latest = events.at(-1); if (latest) { let current = draft.cognitiveCursors.find((item) => item.tenantId === tenantId); if (!current) { current = { tenantId }; draft.cognitiveCursors.push(current); } current.eventId = latest.id; current.recordedAt = latest.recordedAt; } draft.cognitiveCycles.push({ id: uuid(), tenantId, eventCount: unseen.length, observationCount: observations.length, createdAt: now(), actorId }); return draft; });
    for (const observation of observations) await this.propose(tenantId, actorId, { description: `Investigate and safely remediate: ${observation.description}`, origin: 'observation-engine', evidence: observation.evidence, risks: ['Incorrect remediation may reduce availability'], expectedImpact: 'Restore or improve service health', estimate: { effort: 3, cost: 1 }, plan: ['Validate evidence', 'Select registered Runtime job', 'Execute in non-production', 'Validate acceptance criteria'], dependencies: [], confidence: observation.confidence, action: 'cognitive.execute.high', job: null });
    return { observed: unseen.length, observations: observations.length, context: await this.context(tenantId, actorId) };
  }
  async propose(tenantId, actorId, input) { await this.cp.authorize(tenantId, actorId, 'governance:approve'); assertNoSecrets(input); if (!input?.description || !input?.evidence?.length || !input?.risks?.length || !input?.plan?.length) throw new ValidationError('hypothesis requires description, evidence, risks and plan'); const score = priorityScore(input); const hypothesis = { id: uuid(), tenantId, description: String(input.description), origin: input.origin || 'administrator', evidence: input.evidence, risks: input.risks, expectedImpact: input.expectedImpact || null, estimate: input.estimate || {}, plan: input.plan, dependencies: input.dependencies || [], confidence: Number(input.confidence || 0.5), priority: score, priorityFactors: priorityFactors(input), action: input.action || 'cognitive.execute.high', job: input.job || null, status: 'PROPOSED', createdBy: actorId, createdAt: now() }; await this.store.update((state) => { state.cognitiveHypotheses.push(hypothesis); return state; }); await this.publish(hypothesis, 'cognitive.hypothesis.proposed', actorId); return hypothesis; }
  async evaluate(tenantId, actorId, hypothesisId) { const hypothesis = await this.getHypothesis(tenantId, actorId, hypothesisId); if (hypothesis.status !== 'PROPOSED') throw new ValidationError('hypothesis is not proposed'); const decision = this.policy.evaluate(hypothesis.action); const resource = { hypothesisId, jobType: hypothesis.job?.type || null, priority: hypothesis.priority }; const approval = await this.approvals.request(tenantId, actorId, { action: hypothesis.action, resource, rationale: hypothesis.description }); await this.store.update((state) => { const item = state.cognitiveHypotheses.find((entry) => entry.id === hypothesisId); item.status = approval.status === 'approved' ? 'APPROVED' : 'AWAITING_APPROVAL'; item.approvalId = approval.id; item.policyDecision = decision; state.cognitiveDecisions.push({ id: uuid(), tenantId, hypothesisId, decision, approvalId: approval.id, factors: hypothesis.priorityFactors, decidedAt: now(), decidedBy: actorId }); return state; }); await this.publish(hypothesis, 'cognitive.hypothesis.evaluated', actorId); return this.getHypothesis(tenantId, actorId, hypothesisId); }
  async dispatch(tenantId, actorId, hypothesisId) { const hypothesis = await this.getHypothesis(tenantId, actorId, hypothesisId); if (!hypothesis.job) throw new ValidationError('hypothesis is planning-only and has no Runtime job'); const resource = { hypothesisId, jobType: hypothesis.job.type, priority: hypothesis.priority }; await this.approvals.consume(tenantId, actorId, hypothesis.approvalId, { action: hypothesis.action, resource }); const job = await this.jobs.submit(tenantId, actorId, hypothesis.job); await this.store.update((state) => { const item = state.cognitiveHypotheses.find((entry) => entry.id === hypothesisId); item.status = 'DISPATCHED'; item.jobId = job.id; item.dispatchedAt = now(); return state; }); await this.publish(hypothesis, 'cognitive.execution.dispatched', actorId); return { hypothesis: await this.getHypothesis(tenantId, actorId, hypothesisId), job };
  }
  async onJobResult(event) { const state = await this.store.read(); const hypothesis = state.cognitiveHypotheses.find((item) => item.tenantId === event.tenantId && item.jobId === event.data.jobId); if (!hypothesis) return; const success = event.data.status === 'SUCCEEDED'; const validation = { id: uuid(), tenantId: event.tenantId, hypothesisId: hypothesis.id, jobId: event.data.jobId, success, status: event.data.status, acceptance: success ? 'Runtime job completed successfully' : 'Runtime job did not satisfy success criteria', evidence: [`event:${event.id}`], validatedAt: now() }; const reflection = { id: uuid(), tenantId: event.tenantId, hypothesisId: hypothesis.id, expected: hypothesis.expectedImpact, obtained: event.data.status, differences: success ? [] : ['Expected successful execution'], causes: success ? [] : ['Runtime result requires administrator analysis'], learnings: [success ? 'The governed plan completed' : 'The plan needs revision before retry'], createdAt: now() }; await this.store.update((draft) => { draft.cognitiveValidations.push(validation); draft.cognitiveReflections.push(reflection); const item = draft.cognitiveHypotheses.find((entry) => entry.id === hypothesis.id); item.status = success ? 'VALIDATED' : 'FAILED_VALIDATION'; item.completedAt = now(); return draft; }); await this.events.publish({ tenantId: event.tenantId, stream: `hypothesis:${hypothesis.id}`, type: 'cognitive.learning.recorded', source: 'cognitive-core', subject: hypothesis.id, causationId: event.id, data: { actorId: 'cognitive-core', hypothesisId: hypothesis.id, description: hypothesis.description, success, evidence: validation.evidence, reflection: reflection.learnings, confidence: hypothesis.confidence }, idempotencyKey: `cognitive-learning:${hypothesis.id}:${event.id}` }); }
  async getHypothesis(tenantId, actorId, id) { await this.cp.authorize(tenantId, actorId, 'governance:read'); const state = await this.store.read(); const item = state.cognitiveHypotheses.find((entry) => entry.tenantId === tenantId && entry.id === id); if (!item) throw new NotFoundError(`hypothesis not found: ${id}`); return item; }
  async dashboard(tenantId, actorId) { await this.cp.authorize(tenantId, actorId, 'governance:read'); const state = await this.store.read(); const hypotheses = state.cognitiveHypotheses.filter((item) => item.tenantId === tenantId); const decisions = state.cognitiveDecisions.filter((item) => item.tenantId === tenantId); const validations = state.cognitiveValidations.filter((item) => item.tenantId === tenantId); const durations = (pairs) => pairs.filter(([start, end]) => start && end).map(([start, end]) => Date.parse(end) - Date.parse(start)); const average = (values) => values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) : null; const decisionTimes = durations(decisions.map((item) => [hypotheses.find((entry) => entry.id === item.hypothesisId)?.createdAt, item.decidedAt])); const executionTimes = durations(hypotheses.map((item) => [item.dispatchedAt, item.completedAt])); return { goals: state.cognitiveGoals.filter((item) => item.tenantId === tenantId), hypotheses: hypotheses.sort((a, b) => b.priority - a.priority), metrics: { total: hypotheses.length, approved: hypotheses.filter((item) => ['APPROVED', 'DISPATCHED', 'VALIDATED'].includes(item.status)).length, rejected: hypotheses.filter((item) => item.status === 'REJECTED').length, validated: hypotheses.filter((item) => item.status === 'VALIDATED').length, failed: hypotheses.filter((item) => item.status === 'FAILED_VALIDATION').length, averageDecisionMs: average(decisionTimes), averageExecutionMs: average(executionTimes), precision: validations.length ? validations.filter((item) => item.success).length / validations.length : null, successRate: validations.length ? validations.filter((item) => item.success).length / validations.length : null, learnings: state.cognitiveReflections.filter((item) => item.tenantId === tenantId).length } }; }
  async publish(subject, type, actorId) { await this.events.publish({ tenantId: subject.tenantId, stream: `cognitive:${subject.id}`, type, source: 'cognitive-core', subject: subject.id, data: { actorId, id: subject.id, status: subject.status || 'ACTIVE', description: subject.description || subject.title, priority: subject.priority || null }, idempotencyKey: `${type}:${subject.id}:${subject.status || 'new'}` }); }
}

function priorityFactors(input) { return { security: Number(input.security || 5), availability: Number(input.availability || 5), impact: Number(input.impact || 5), effort: Number(input.estimate?.effort || 5), risk: Number(input.risk || 5), cost: Number(input.estimate?.cost || 5), value: Number(input.value || 5) }; }
function priorityScore(input) { const f = priorityFactors(input); return Number((f.security * 3 + f.availability * 3 + f.impact * 2 + f.value * 2 - f.effort - f.risk - f.cost).toFixed(2)); }
function now() { return new Date().toISOString(); }
module.exports = { CognitiveCore, priorityScore, priorityFactors };
