const fs = require('fs');
const path = require('path');
const registries = require('./Registries');

class Container {
  constructor(kernel) {
    this.kernel = kernel;
    this.instances = new Map();
  }
  
  get(name) {
    if (this.instances.has(name)) return this.instances.get(name);
    const meta = this.kernel.registries.ModuleRegistry.get(name);
    if (!meta) {
      // Fallback: It might be already in a hardcoded old-school map or unmigrated class.
      // Returning null lets the caller deal with it, but for a true strict DI, we could throw.
      return null;
    }
    
    if (meta.create && typeof meta.create === 'function') {
      const instance = meta.create(this);
      this.instances.set(name, instance);
      return instance;
    }
    return null; // Not instantiable via DI yet
  }
}

class Kernel {
  constructor() {
    this.registries = {
      ModuleRegistry: new registries.ModuleRegistry(),
      CapabilityRegistry: new registries.CapabilityRegistry(),
      ServiceRegistry: new registries.ServiceRegistry(),
      KnowledgeRegistry: new registries.KnowledgeRegistry(),
      MissionRegistry: new registries.MissionRegistry(),
      WorkerRegistry: new registries.WorkerRegistry(),
      ProjectRegistry: new registries.ProjectRegistry(),
      ProviderRegistry: new registries.ProviderRegistry(),
      EvolutionRegistry: new registries.EvolutionRegistry(),
      RuntimeRegistry: new registries.RuntimeRegistry(),
      RouteRegistry: new registries.RouteRegistry(),
      EventRegistry: new registries.EventRegistry(),
      PluginRegistry: new registries.PluginRegistry()
    };
    
    this.container = new Container(this);
    this.autoGeneratedMissions = [];
    this.graph = { nodes: [], edges: [] };
  }

  async boot(srcDir) {
    console.log('[Kernel] Boot sequence initiated...');
    this.scanDirectory(srcDir);
    
    const pluginManager = this.container.get('PluginManager');
    if (pluginManager) {
      pluginManager.scan(path.join(srcDir, 'plugins'));
    } else {
      console.warn('[Kernel] PluginManager not found during boot.');
    }

    this.generateMissions();
    this.writeArtifacts();
    console.log('[Kernel] Boot sequence complete. Operating System is alive.');
  }

  scanDirectory(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      if (fs.statSync(fullPath).isDirectory()) {
        this.scanDirectory(fullPath);
      } else if (file.endsWith('.js')) {
        this.inspectFile(fullPath);
      }
    }
  }

  inspectFile(fullPath) {
    try {
      // Emulate require to see if it exposes Hybrid DI Option C exports
      const exported = require(fullPath);
      
      // Look for Option C signature
      if (exported && exported.type && exported.name && exported.version) {
        this.registerModule(exported, fullPath);
      } else {
        // Legacy modules might export Classes directly
        for (const key in exported) {
          if (typeof exported[key] === 'function' && exported[key].toString().startsWith('class')) {
            this.registerLegacyModule(key, fullPath);
          }
        }
      }
    } catch (e) {
      // Ignore files that fail to load independently (mostly old monolithic tight-coupled scripts)
      // They will be picked up over time when migrated to Hybrid DI Option C.
    }
  }

  registerModule(meta, filePath) {
    const isDuplicate = this.registries.ModuleRegistry.has(meta.name);
    
    // Register in global
    this.registries.ModuleRegistry.register(meta.name, { ...meta, filePath });
    
    // Distribute to specific registries based on Type
    switch (meta.type) {
      case 'worker': this.registries.WorkerRegistry.register(meta.name, meta); break;
      case 'service': this.registries.ServiceRegistry.register(meta.name, meta); break;
      case 'provider': this.registries.ProviderRegistry.register(meta.name, meta); break;
      case 'mission': this.registries.MissionRegistry.register(meta.name, meta); break;
      case 'route': this.registries.RouteRegistry.register(meta.name, meta); break;
      case 'plugin': this.registries.PluginRegistry.register(meta.name, meta); break;
      case 'event': this.registries.EventRegistry.register(meta.name, meta); break;
      // others...
    }

    if (meta.capabilities) {
      meta.capabilities.forEach(cap => this.registries.CapabilityRegistry.register(cap, { owner: meta.name }));
    }

    // Graph Construction
    this.graph.nodes.push({ id: meta.name, type: meta.type });
    if (meta.requires) {
      meta.requires.forEach(req => {
        this.graph.edges.push({ from: meta.name, to: req });
      });
    }

    if (isDuplicate) {
      this.autoGeneratedMissions.push({
        intent: `Merge Candidate detected: ${meta.name}`,
        reason: `Duplicated module found across files.`,
        action: 'Review'
      });
    }
    
    if (meta.requires && meta.requires.length === 0 && meta.type !== 'provider') {
      this.autoGeneratedMissions.push({
        intent: `Review isolated module: ${meta.name}`,
        reason: `Module has no dependencies.`,
        action: 'Review'
      });
    }
  }

  registerLegacyModule(className, filePath) {
    // Treat legacy classes as "services" implicitly to catalog them
    const meta = { name: className, type: 'legacy', filePath };
    this.registries.ModuleRegistry.register(className, meta);
  }

  generateMissions() {
    if (this.autoGeneratedMissions.length > 0) {
      console.log(`[Kernel] Discovered ${this.autoGeneratedMissions.length} internal optimization missions.`);
      // In a real system, we would inject these into the MissionEngine
    }
  }

  writeArtifacts() {
    const runtimeDir = path.join(__dirname, '../../runtime');
    if (!fs.existsSync(runtimeDir)) fs.mkdirSync(runtimeDir, { recursive: true });

    // 1. runtime-manifest.json
    const manifest = {
      version: "1.0",
      modules: this.registries.ModuleRegistry.getAll().length,
      plugins: this.registries.PluginRegistry.getAll().length,
      workers: this.registries.WorkerRegistry.getAll().length,
      services: this.registries.ServiceRegistry.getAll().length,
      providers: this.registries.ProviderRegistry.getAll().length,
      projects: this.registries.ProjectRegistry.getAll().length,
      routes: this.registries.RouteRegistry.getAll().length,
      events: this.registries.EventRegistry.getAll().length,
      knowledgeStores: this.registries.KnowledgeRegistry.getAll().length,
      capabilities: this.registries.CapabilityRegistry.getAll().length
    };
    fs.writeFileSync(path.join(runtimeDir, 'runtime-manifest.json'), JSON.stringify(manifest, null, 2));

    // 2. runtime-graph.json
    fs.writeFileSync(path.join(runtimeDir, 'runtime-graph.json'), JSON.stringify(this.graph, null, 2));

    // 3. index.json
    const index = {
      modules: this.registries.ModuleRegistry.getAll(),
      capabilities: this.registries.CapabilityRegistry.getAll()
    };
    fs.writeFileSync(path.join(runtimeDir, 'index.json'), JSON.stringify(index, null, 2));

    // 4. dna.json
    const dna = {
      System: {
        Kernel: {
          Registries: Object.keys(this.registries).reduce((acc, k) => {
            acc[k] = this.registries[k].getAll().map(i => i.name || i);
            return acc;
          }, {})
        }
      }
    };
    fs.writeFileSync(path.join(runtimeDir, 'dna.json'), JSON.stringify(dna, null, 2));
  }
}

module.exports = { Kernel, Container };
