const STATE_MACHINE = Object.freeze({
  BOOT: 'BOOT',
  READY: 'READY',
  ONLINE: 'ONLINE',
  BUSY: 'BUSY',
  LEARNING: 'LEARNING',
  UPDATING: 'UPDATING',
  ERROR: 'ERROR',
  RECOVERY: 'RECOVERY',
  SAFE_MODE: 'SAFE_MODE',
  OFFLINE: 'OFFLINE',
  SHUTDOWN: 'SHUTDOWN'
});

module.exports = { STATE_MACHINE };
